/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessoRapidoRouteImport } from './routes/acesso-rapido'
import { Route as AlbunsRouteImport } from './routes/albuns'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as EmpirePlayRouteImport } from './routes/empire-play'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as SocialRouteImport } from './routes/social'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as TvRouteImport } from './routes/tv'
import { Route as AcoesAlbumRouteImport } from './routes/acoes.album'
import { Route as AcoesCinemaRouteImport } from './routes/acoes.cinema'
import { Route as AcoesTourRouteImport } from './routes/acoes.tour'
import { Route as AlbumIdRouteImport } from './routes/album.$id'
import { Route as ArtistasIndexRouteImport } from './routes/artistas.index'
import { Route as EmpirePlayIndexRouteImport } from './routes/empire-play.index'
import { Route as EmpirePlayAlbunsRouteImport } from './routes/empire-play.albuns'
import { Route as EmpirePlayAlbunsAntigosRouteImport } from './routes/empire-play.albuns-antigos'
import { Route as EmpirePlayForumRouteImport } from './routes/empire-play.forum'
import { Route as EmpirePlayGestaoRouteImport } from './routes/empire-play.gestao'
import { Route as EmpirePlayMusicasRouteImport } from './routes/empire-play.musicas'
import { Route as EmpirePlayVideosRouteImport } from './routes/empire-play.videos'
import { Route as PontoIndexRouteImport } from './routes/ponto.index'
import { Route as PontoDistribuirRouteImport } from './routes/ponto.distribuir'
import { Route as PontoPlaylistsRouteImport } from './routes/ponto.playlists'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as ToursNomeRouteImport } from './routes/tours.$nome'
import { Route as AlbumIdEditarRouteImport } from './routes/album.$id.editar'
import { Route as ArtistasNomeIndexRouteImport } from './routes/artistas.$nome.index'
import { Route as EmpirePlayAlbunsAntigosIndexRouteImport } from './routes/empire-play.albuns-antigos.index'
import { Route as EmpirePlayAlbunsAntigosIdRouteImport } from './routes/empire-play.albuns-antigos.$id'
import { Route as EmpirePlayGestaoIndexRouteImport } from './routes/empire-play.gestao.index'
import { Route as EmpirePlayGestaoAlbumAntigoRouteImport } from './routes/empire-play.gestao.album-antigo'
import { Route as EmpirePlayPlaylistsIndexRouteImport } from './routes/empire-play.playlists.index'
import { Route as EmpirePlayPlaylistsIdRouteImport } from './routes/empire-play.playlists.$id'
import { Route as EmpirePlayPlaylistsNovaRouteImport } from './routes/empire-play.playlists.nova'
import { Route as PontoDistribuirIndexRouteImport } from './routes/ponto.distribuir.index'
import { Route as PontoDistribuirPlanilhaRouteImport } from './routes/ponto.distribuir.planilha'
import { Route as PontoPlaylistsIndexRouteImport } from './routes/ponto.playlists.index'
import { Route as PontoPlaylistsPlanilhaRouteImport } from './routes/ponto.playlists.planilha'
import { Route as EmpirePlayPlaylistsIdEditarRouteImport } from './routes/empire-play.playlists.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRapidoRoute = AcessoRapidoRouteImport.update({
  id: '/acesso-rapido',
  path: '/acesso-rapido',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbunsRoute = AlbunsRouteImport.update({
  id: '/albuns',
  path: '/albuns',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpirePlayRoute = EmpirePlayRouteImport.update({
  id: '/empire-play',
  path: '/empire-play',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesAlbumRoute = AcoesAlbumRouteImport.update({
  id: '/acoes/album',
  path: '/acoes/album',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesCinemaRoute = AcoesCinemaRouteImport.update({
  id: '/acoes/cinema',
  path: '/acoes/cinema',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesTourRoute = AcoesTourRouteImport.update({
  id: '/acoes/tour',
  path: '/acoes/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdRoute = AlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistasIndexRoute = ArtistasIndexRouteImport.update({
  id: '/artistas/',
  path: '/artistas/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpirePlayIndexRoute = EmpirePlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const EmpirePlayAlbunsRoute = EmpirePlayAlbunsRouteImport.update({
  id: '/albuns',
  path: '/albuns',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const EmpirePlayAlbunsAntigosRoute = EmpirePlayAlbunsAntigosRouteImport.update({
  id: '/albuns-antigos',
  path: '/albuns-antigos',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const EmpirePlayForumRoute = EmpirePlayForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const EmpirePlayGestaoRoute = EmpirePlayGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const EmpirePlayMusicasRoute = EmpirePlayMusicasRouteImport.update({
  id: '/musicas',
  path: '/musicas',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const EmpirePlayVideosRoute = EmpirePlayVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const PontoIndexRoute = PontoIndexRouteImport.update({
  id: '/ponto/',
  path: '/ponto/',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoDistribuirRoute = PontoDistribuirRouteImport.update({
  id: '/ponto/distribuir',
  path: '/ponto/distribuir',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoPlaylistsRoute = PontoPlaylistsRouteImport.update({
  id: '/ponto/playlists',
  path: '/ponto/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursNomeRoute = ToursNomeRouteImport.update({
  id: '/tours/$nome',
  path: '/tours/$nome',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdEditarRoute = AlbumIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AlbumIdRoute,
} as any)
const ArtistasNomeIndexRoute = ArtistasNomeIndexRouteImport.update({
  id: '/artistas/$nome/',
  path: '/artistas/$nome/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpirePlayAlbunsAntigosIndexRoute =
  EmpirePlayAlbunsAntigosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EmpirePlayAlbunsAntigosRoute,
  } as any)
const EmpirePlayAlbunsAntigosIdRoute =
  EmpirePlayAlbunsAntigosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => EmpirePlayAlbunsAntigosRoute,
  } as any)
const EmpirePlayGestaoIndexRoute = EmpirePlayGestaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpirePlayGestaoRoute,
} as any)
const EmpirePlayGestaoAlbumAntigoRoute =
  EmpirePlayGestaoAlbumAntigoRouteImport.update({
    id: '/album-antigo',
    path: '/album-antigo',
    getParentRoute: () => EmpirePlayGestaoRoute,
  } as any)
const EmpirePlayPlaylistsIndexRoute =
  EmpirePlayPlaylistsIndexRouteImport.update({
    id: '/playlists/',
    path: '/playlists/',
    getParentRoute: () => EmpirePlayRoute,
  } as any)
const EmpirePlayPlaylistsIdRoute = EmpirePlayPlaylistsIdRouteImport.update({
  id: '/playlists/$id',
  path: '/playlists/$id',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const EmpirePlayPlaylistsNovaRoute = EmpirePlayPlaylistsNovaRouteImport.update({
  id: '/playlists/nova',
  path: '/playlists/nova',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const PontoDistribuirIndexRoute = PontoDistribuirIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PontoDistribuirRoute,
} as any)
const PontoDistribuirPlanilhaRoute = PontoDistribuirPlanilhaRouteImport.update({
  id: '/planilha',
  path: '/planilha',
  getParentRoute: () => PontoDistribuirRoute,
} as any)
const PontoPlaylistsIndexRoute = PontoPlaylistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PontoPlaylistsRoute,
} as any)
const PontoPlaylistsPlanilhaRoute = PontoPlaylistsPlanilhaRouteImport.update({
  id: '/planilha',
  path: '/planilha',
  getParentRoute: () => PontoPlaylistsRoute,
} as any)
const EmpirePlayPlaylistsIdEditarRoute =
  EmpirePlayPlaylistsIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => EmpirePlayPlaylistsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-rapido': typeof AcessoRapidoRoute
  '/albuns': typeof AlbunsRoute
  '/charts': typeof ChartsRoute
  '/empire-play': typeof EmpirePlayRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/social': typeof SocialRoute
  '/tutorial': typeof TutorialRoute
  '/tv': typeof TvRoute
  '/acoes/album': typeof AcoesAlbumRoute
  '/acoes/cinema': typeof AcoesCinemaRoute
  '/acoes/tour': typeof AcoesTourRoute
  '/album/$id': typeof AlbumIdRouteWithChildren
  '/empire-play/albuns': typeof EmpirePlayAlbunsRoute
  '/empire-play/albuns-antigos': typeof EmpirePlayAlbunsAntigosRouteWithChildren
  '/empire-play/forum': typeof EmpirePlayForumRoute
  '/empire-play/gestao': typeof EmpirePlayGestaoRouteWithChildren
  '/empire-play/musicas': typeof EmpirePlayMusicasRoute
  '/empire-play/videos': typeof EmpirePlayVideosRoute
  '/ponto/distribuir': typeof PontoDistribuirRouteWithChildren
  '/ponto/playlists': typeof PontoPlaylistsRouteWithChildren
  '/tours/$nome': typeof ToursNomeRoute
  '/artistas/': typeof ArtistasIndexRoute
  '/empire-play/': typeof EmpirePlayIndexRoute
  '/ponto/': typeof PontoIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/album/$id/editar': typeof AlbumIdEditarRoute
  '/empire-play/albuns-antigos/$id': typeof EmpirePlayAlbunsAntigosIdRoute
  '/empire-play/gestao/album-antigo': typeof EmpirePlayGestaoAlbumAntigoRoute
  '/empire-play/playlists/$id': typeof EmpirePlayPlaylistsIdRouteWithChildren
  '/empire-play/playlists/nova': typeof EmpirePlayPlaylistsNovaRoute
  '/ponto/distribuir/planilha': typeof PontoDistribuirPlanilhaRoute
  '/ponto/playlists/planilha': typeof PontoPlaylistsPlanilhaRoute
  '/artistas/$nome/': typeof ArtistasNomeIndexRoute
  '/empire-play/albuns-antigos/': typeof EmpirePlayAlbunsAntigosIndexRoute
  '/empire-play/gestao/': typeof EmpirePlayGestaoIndexRoute
  '/empire-play/playlists/': typeof EmpirePlayPlaylistsIndexRoute
  '/ponto/distribuir/': typeof PontoDistribuirIndexRoute
  '/ponto/playlists/': typeof PontoPlaylistsIndexRoute
  '/empire-play/playlists/$id/editar': typeof EmpirePlayPlaylistsIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-rapido': typeof AcessoRapidoRoute
  '/albuns': typeof AlbunsRoute
  '/charts': typeof ChartsRoute
  '/perfil': typeof PerfilRoute
  '/social': typeof SocialRoute
  '/tutorial': typeof TutorialRoute
  '/tv': typeof TvRoute
  '/acoes/album': typeof AcoesAlbumRoute
  '/acoes/cinema': typeof AcoesCinemaRoute
  '/acoes/tour': typeof AcoesTourRoute
  '/album/$id': typeof AlbumIdRouteWithChildren
  '/empire-play/albuns': typeof EmpirePlayAlbunsRoute
  '/empire-play/forum': typeof EmpirePlayForumRoute
  '/empire-play/musicas': typeof EmpirePlayMusicasRoute
  '/empire-play/videos': typeof EmpirePlayVideosRoute
  '/tours/$nome': typeof ToursNomeRoute
  '/artistas': typeof ArtistasIndexRoute
  '/empire-play': typeof EmpirePlayIndexRoute
  '/ponto': typeof PontoIndexRoute
  '/tours': typeof ToursIndexRoute
  '/album/$id/editar': typeof AlbumIdEditarRoute
  '/empire-play/albuns-antigos/$id': typeof EmpirePlayAlbunsAntigosIdRoute
  '/empire-play/gestao/album-antigo': typeof EmpirePlayGestaoAlbumAntigoRoute
  '/empire-play/playlists/$id': typeof EmpirePlayPlaylistsIdRouteWithChildren
  '/empire-play/playlists/nova': typeof EmpirePlayPlaylistsNovaRoute
  '/ponto/distribuir/planilha': typeof PontoDistribuirPlanilhaRoute
  '/ponto/playlists/planilha': typeof PontoPlaylistsPlanilhaRoute
  '/artistas/$nome': typeof ArtistasNomeIndexRoute
  '/empire-play/albuns-antigos': typeof EmpirePlayAlbunsAntigosIndexRoute
  '/empire-play/gestao': typeof EmpirePlayGestaoIndexRoute
  '/empire-play/playlists': typeof EmpirePlayPlaylistsIndexRoute
  '/ponto/distribuir': typeof PontoDistribuirIndexRoute
  '/ponto/playlists': typeof PontoPlaylistsIndexRoute
  '/empire-play/playlists/$id/editar': typeof EmpirePlayPlaylistsIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso-rapido': typeof AcessoRapidoRoute
  '/albuns': typeof AlbunsRoute
  '/charts': typeof ChartsRoute
  '/empire-play': typeof EmpirePlayRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/social': typeof SocialRoute
  '/tutorial': typeof TutorialRoute
  '/tv': typeof TvRoute
  '/acoes/album': typeof AcoesAlbumRoute
  '/acoes/cinema': typeof AcoesCinemaRoute
  '/acoes/tour': typeof AcoesTourRoute
  '/album/$id': typeof AlbumIdRouteWithChildren
  '/empire-play/albuns': typeof EmpirePlayAlbunsRoute
  '/empire-play/albuns-antigos': typeof EmpirePlayAlbunsAntigosRouteWithChildren
  '/empire-play/forum': typeof EmpirePlayForumRoute
  '/empire-play/gestao': typeof EmpirePlayGestaoRouteWithChildren
  '/empire-play/musicas': typeof EmpirePlayMusicasRoute
  '/empire-play/videos': typeof EmpirePlayVideosRoute
  '/ponto/distribuir': typeof PontoDistribuirRouteWithChildren
  '/ponto/playlists': typeof PontoPlaylistsRouteWithChildren
  '/tours/$nome': typeof ToursNomeRoute
  '/artistas/': typeof ArtistasIndexRoute
  '/empire-play/': typeof EmpirePlayIndexRoute
  '/ponto/': typeof PontoIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/album/$id/editar': typeof AlbumIdEditarRoute
  '/empire-play/albuns-antigos/$id': typeof EmpirePlayAlbunsAntigosIdRoute
  '/empire-play/gestao/album-antigo': typeof EmpirePlayGestaoAlbumAntigoRoute
  '/empire-play/playlists/$id': typeof EmpirePlayPlaylistsIdRouteWithChildren
  '/empire-play/playlists/nova': typeof EmpirePlayPlaylistsNovaRoute
  '/ponto/distribuir/planilha': typeof PontoDistribuirPlanilhaRoute
  '/ponto/playlists/planilha': typeof PontoPlaylistsPlanilhaRoute
  '/artistas/$nome/': typeof ArtistasNomeIndexRoute
  '/empire-play/albuns-antigos/': typeof EmpirePlayAlbunsAntigosIndexRoute
  '/empire-play/gestao/': typeof EmpirePlayGestaoIndexRoute
  '/empire-play/playlists/': typeof EmpirePlayPlaylistsIndexRoute
  '/ponto/distribuir/': typeof PontoDistribuirIndexRoute
  '/ponto/playlists/': typeof PontoPlaylistsIndexRoute
  '/empire-play/playlists/$id/editar': typeof EmpirePlayPlaylistsIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-rapido'
    | '/albuns'
    | '/charts'
    | '/empire-play'
    | '/perfil'
    | '/social'
    | '/tutorial'
    | '/tv'
    | '/acoes/album'
    | '/acoes/cinema'
    | '/acoes/tour'
    | '/album/$id'
    | '/empire-play/albuns'
    | '/empire-play/albuns-antigos'
    | '/empire-play/forum'
    | '/empire-play/gestao'
    | '/empire-play/musicas'
    | '/empire-play/videos'
    | '/ponto/distribuir'
    | '/ponto/playlists'
    | '/tours/$nome'
    | '/artistas/'
    | '/empire-play/'
    | '/ponto/'
    | '/tours/'
    | '/album/$id/editar'
    | '/empire-play/albuns-antigos/$id'
    | '/empire-play/gestao/album-antigo'
    | '/empire-play/playlists/$id'
    | '/empire-play/playlists/nova'
    | '/ponto/distribuir/planilha'
    | '/ponto/playlists/planilha'
    | '/artistas/$nome/'
    | '/empire-play/albuns-antigos/'
    | '/empire-play/gestao/'
    | '/empire-play/playlists/'
    | '/ponto/distribuir/'
    | '/ponto/playlists/'
    | '/empire-play/playlists/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-rapido'
    | '/albuns'
    | '/charts'
    | '/perfil'
    | '/social'
    | '/tutorial'
    | '/tv'
    | '/acoes/album'
    | '/acoes/cinema'
    | '/acoes/tour'
    | '/album/$id'
    | '/empire-play/albuns'
    | '/empire-play/forum'
    | '/empire-play/musicas'
    | '/empire-play/videos'
    | '/tours/$nome'
    | '/artistas'
    | '/empire-play'
    | '/ponto'
    | '/tours'
    | '/album/$id/editar'
    | '/empire-play/albuns-antigos/$id'
    | '/empire-play/gestao/album-antigo'
    | '/empire-play/playlists/$id'
    | '/empire-play/playlists/nova'
    | '/ponto/distribuir/planilha'
    | '/ponto/playlists/planilha'
    | '/artistas/$nome'
    | '/empire-play/albuns-antigos'
    | '/empire-play/gestao'
    | '/empire-play/playlists'
    | '/ponto/distribuir'
    | '/ponto/playlists'
    | '/empire-play/playlists/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/acesso-rapido'
    | '/albuns'
    | '/charts'
    | '/empire-play'
    | '/perfil'
    | '/social'
    | '/tutorial'
    | '/tv'
    | '/acoes/album'
    | '/acoes/cinema'
    | '/acoes/tour'
    | '/album/$id'
    | '/empire-play/albuns'
    | '/empire-play/albuns-antigos'
    | '/empire-play/forum'
    | '/empire-play/gestao'
    | '/empire-play/musicas'
    | '/empire-play/videos'
    | '/ponto/distribuir'
    | '/ponto/playlists'
    | '/tours/$nome'
    | '/artistas/'
    | '/empire-play/'
    | '/ponto/'
    | '/tours/'
    | '/album/$id/editar'
    | '/empire-play/albuns-antigos/$id'
    | '/empire-play/gestao/album-antigo'
    | '/empire-play/playlists/$id'
    | '/empire-play/playlists/nova'
    | '/ponto/distribuir/planilha'
    | '/ponto/playlists/planilha'
    | '/artistas/$nome/'
    | '/empire-play/albuns-antigos/'
    | '/empire-play/gestao/'
    | '/empire-play/playlists/'
    | '/ponto/distribuir/'
    | '/ponto/playlists/'
    | '/empire-play/playlists/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoRapidoRoute: typeof AcessoRapidoRoute
  AlbunsRoute: typeof AlbunsRoute
  ChartsRoute: typeof ChartsRoute
  EmpirePlayRoute: typeof EmpirePlayRouteWithChildren
  PerfilRoute: typeof PerfilRoute
  SocialRoute: typeof SocialRoute
  TutorialRoute: typeof TutorialRoute
  TvRoute: typeof TvRoute
  AcoesAlbumRoute: typeof AcoesAlbumRoute
  AcoesCinemaRoute: typeof AcoesCinemaRoute
  AcoesTourRoute: typeof AcoesTourRoute
  AlbumIdRoute: typeof AlbumIdRouteWithChildren
  PontoDistribuirRoute: typeof PontoDistribuirRouteWithChildren
  PontoPlaylistsRoute: typeof PontoPlaylistsRouteWithChildren
  ToursNomeRoute: typeof ToursNomeRoute
  ArtistasIndexRoute: typeof ArtistasIndexRoute
  PontoIndexRoute: typeof PontoIndexRoute
  ToursIndexRoute: typeof ToursIndexRoute
  ArtistasNomeIndexRoute: typeof ArtistasNomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-rapido': {
      id: '/acesso-rapido'
      path: '/acesso-rapido'
      fullPath: '/acesso-rapido'
      preLoaderRoute: typeof AcessoRapidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albuns': {
      id: '/albuns'
      path: '/albuns'
      fullPath: '/albuns'
      preLoaderRoute: typeof AlbunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empire-play': {
      id: '/empire-play'
      path: '/empire-play'
      fullPath: '/empire-play'
      preLoaderRoute: typeof EmpirePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes/album': {
      id: '/acoes/album'
      path: '/acoes/album'
      fullPath: '/acoes/album'
      preLoaderRoute: typeof AcoesAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes/cinema': {
      id: '/acoes/cinema'
      path: '/acoes/cinema'
      fullPath: '/acoes/cinema'
      preLoaderRoute: typeof AcoesCinemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes/tour': {
      id: '/acoes/tour'
      path: '/acoes/tour'
      fullPath: '/acoes/tour'
      preLoaderRoute: typeof AcoesTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id': {
      id: '/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistas/': {
      id: '/artistas/'
      path: '/artistas'
      fullPath: '/artistas/'
      preLoaderRoute: typeof ArtistasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empire-play/': {
      id: '/empire-play/'
      path: '/'
      fullPath: '/empire-play/'
      preLoaderRoute: typeof EmpirePlayIndexRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/empire-play/albuns': {
      id: '/empire-play/albuns'
      path: '/albuns'
      fullPath: '/empire-play/albuns'
      preLoaderRoute: typeof EmpirePlayAlbunsRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/empire-play/albuns-antigos': {
      id: '/empire-play/albuns-antigos'
      path: '/albuns-antigos'
      fullPath: '/empire-play/albuns-antigos'
      preLoaderRoute: typeof EmpirePlayAlbunsAntigosRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/empire-play/forum': {
      id: '/empire-play/forum'
      path: '/forum'
      fullPath: '/empire-play/forum'
      preLoaderRoute: typeof EmpirePlayForumRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/empire-play/gestao': {
      id: '/empire-play/gestao'
      path: '/gestao'
      fullPath: '/empire-play/gestao'
      preLoaderRoute: typeof EmpirePlayGestaoRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/empire-play/musicas': {
      id: '/empire-play/musicas'
      path: '/musicas'
      fullPath: '/empire-play/musicas'
      preLoaderRoute: typeof EmpirePlayMusicasRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/empire-play/videos': {
      id: '/empire-play/videos'
      path: '/videos'
      fullPath: '/empire-play/videos'
      preLoaderRoute: typeof EmpirePlayVideosRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/ponto/': {
      id: '/ponto/'
      path: '/ponto'
      fullPath: '/ponto/'
      preLoaderRoute: typeof PontoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto/distribuir': {
      id: '/ponto/distribuir'
      path: '/ponto/distribuir'
      fullPath: '/ponto/distribuir'
      preLoaderRoute: typeof PontoDistribuirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto/playlists': {
      id: '/ponto/playlists'
      path: '/ponto/playlists'
      fullPath: '/ponto/playlists'
      preLoaderRoute: typeof PontoPlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$nome': {
      id: '/tours/$nome'
      path: '/tours/$nome'
      fullPath: '/tours/$nome'
      preLoaderRoute: typeof ToursNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id/editar': {
      id: '/album/$id/editar'
      path: '/editar'
      fullPath: '/album/$id/editar'
      preLoaderRoute: typeof AlbumIdEditarRouteImport
      parentRoute: typeof AlbumIdRoute
    }
    '/artistas/$nome/': {
      id: '/artistas/$nome/'
      path: '/artistas/$nome'
      fullPath: '/artistas/$nome/'
      preLoaderRoute: typeof ArtistasNomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empire-play/albuns-antigos/': {
      id: '/empire-play/albuns-antigos/'
      path: '/'
      fullPath: '/empire-play/albuns-antigos/'
      preLoaderRoute: typeof EmpirePlayAlbunsAntigosIndexRouteImport
      parentRoute: typeof EmpirePlayAlbunsAntigosRoute
    }
    '/empire-play/albuns-antigos/$id': {
      id: '/empire-play/albuns-antigos/$id'
      path: '/$id'
      fullPath: '/empire-play/albuns-antigos/$id'
      preLoaderRoute: typeof EmpirePlayAlbunsAntigosIdRouteImport
      parentRoute: typeof EmpirePlayAlbunsAntigosRoute
    }
    '/empire-play/gestao/': {
      id: '/empire-play/gestao/'
      path: '/'
      fullPath: '/empire-play/gestao/'
      preLoaderRoute: typeof EmpirePlayGestaoIndexRouteImport
      parentRoute: typeof EmpirePlayGestaoRoute
    }
    '/empire-play/gestao/album-antigo': {
      id: '/empire-play/gestao/album-antigo'
      path: '/album-antigo'
      fullPath: '/empire-play/gestao/album-antigo'
      preLoaderRoute: typeof EmpirePlayGestaoAlbumAntigoRouteImport
      parentRoute: typeof EmpirePlayGestaoRoute
    }
    '/empire-play/playlists/': {
      id: '/empire-play/playlists/'
      path: '/playlists'
      fullPath: '/empire-play/playlists/'
      preLoaderRoute: typeof EmpirePlayPlaylistsIndexRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/empire-play/playlists/$id': {
      id: '/empire-play/playlists/$id'
      path: '/playlists/$id'
      fullPath: '/empire-play/playlists/$id'
      preLoaderRoute: typeof EmpirePlayPlaylistsIdRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/empire-play/playlists/nova': {
      id: '/empire-play/playlists/nova'
      path: '/playlists/nova'
      fullPath: '/empire-play/playlists/nova'
      preLoaderRoute: typeof EmpirePlayPlaylistsNovaRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/ponto/distribuir/': {
      id: '/ponto/distribuir/'
      path: '/'
      fullPath: '/ponto/distribuir/'
      preLoaderRoute: typeof PontoDistribuirIndexRouteImport
      parentRoute: typeof PontoDistribuirRoute
    }
    '/ponto/distribuir/planilha': {
      id: '/ponto/distribuir/planilha'
      path: '/planilha'
      fullPath: '/ponto/distribuir/planilha'
      preLoaderRoute: typeof PontoDistribuirPlanilhaRouteImport
      parentRoute: typeof PontoDistribuirRoute
    }
    '/ponto/playlists/': {
      id: '/ponto/playlists/'
      path: '/'
      fullPath: '/ponto/playlists/'
      preLoaderRoute: typeof PontoPlaylistsIndexRouteImport
      parentRoute: typeof PontoPlaylistsRoute
    }
    '/ponto/playlists/planilha': {
      id: '/ponto/playlists/planilha'
      path: '/planilha'
      fullPath: '/ponto/playlists/planilha'
      preLoaderRoute: typeof PontoPlaylistsPlanilhaRouteImport
      parentRoute: typeof PontoPlaylistsRoute
    }
    '/empire-play/playlists/$id/editar': {
      id: '/empire-play/playlists/$id/editar'
      path: '/editar'
      fullPath: '/empire-play/playlists/$id/editar'
      preLoaderRoute: typeof EmpirePlayPlaylistsIdEditarRouteImport
      parentRoute: typeof EmpirePlayPlaylistsIdRoute
    }
  }
}

interface EmpirePlayAlbunsAntigosRouteChildren {
  EmpirePlayAlbunsAntigosIdRoute: typeof EmpirePlayAlbunsAntigosIdRoute
  EmpirePlayAlbunsAntigosIndexRoute: typeof EmpirePlayAlbunsAntigosIndexRoute
}

const EmpirePlayAlbunsAntigosRouteChildren: EmpirePlayAlbunsAntigosRouteChildren =
  {
    EmpirePlayAlbunsAntigosIdRoute: EmpirePlayAlbunsAntigosIdRoute,
    EmpirePlayAlbunsAntigosIndexRoute: EmpirePlayAlbunsAntigosIndexRoute,
  }

const EmpirePlayAlbunsAntigosRouteWithChildren =
  EmpirePlayAlbunsAntigosRoute._addFileChildren(
    EmpirePlayAlbunsAntigosRouteChildren,
  )

interface EmpirePlayGestaoRouteChildren {
  EmpirePlayGestaoAlbumAntigoRoute: typeof EmpirePlayGestaoAlbumAntigoRoute
  EmpirePlayGestaoIndexRoute: typeof EmpirePlayGestaoIndexRoute
}

const EmpirePlayGestaoRouteChildren: EmpirePlayGestaoRouteChildren = {
  EmpirePlayGestaoAlbumAntigoRoute: EmpirePlayGestaoAlbumAntigoRoute,
  EmpirePlayGestaoIndexRoute: EmpirePlayGestaoIndexRoute,
}

const EmpirePlayGestaoRouteWithChildren =
  EmpirePlayGestaoRoute._addFileChildren(EmpirePlayGestaoRouteChildren)

interface EmpirePlayPlaylistsIdRouteChildren {
  EmpirePlayPlaylistsIdEditarRoute: typeof EmpirePlayPlaylistsIdEditarRoute
}

const EmpirePlayPlaylistsIdRouteChildren: EmpirePlayPlaylistsIdRouteChildren = {
  EmpirePlayPlaylistsIdEditarRoute: EmpirePlayPlaylistsIdEditarRoute,
}

const EmpirePlayPlaylistsIdRouteWithChildren =
  EmpirePlayPlaylistsIdRoute._addFileChildren(
    EmpirePlayPlaylistsIdRouteChildren,
  )

interface EmpirePlayRouteChildren {
  EmpirePlayAlbunsRoute: typeof EmpirePlayAlbunsRoute
  EmpirePlayAlbunsAntigosRoute: typeof EmpirePlayAlbunsAntigosRouteWithChildren
  EmpirePlayForumRoute: typeof EmpirePlayForumRoute
  EmpirePlayGestaoRoute: typeof EmpirePlayGestaoRouteWithChildren
  EmpirePlayMusicasRoute: typeof EmpirePlayMusicasRoute
  EmpirePlayVideosRoute: typeof EmpirePlayVideosRoute
  EmpirePlayIndexRoute: typeof EmpirePlayIndexRoute
  EmpirePlayPlaylistsIdRoute: typeof EmpirePlayPlaylistsIdRouteWithChildren
  EmpirePlayPlaylistsNovaRoute: typeof EmpirePlayPlaylistsNovaRoute
  EmpirePlayPlaylistsIndexRoute: typeof EmpirePlayPlaylistsIndexRoute
}

const EmpirePlayRouteChildren: EmpirePlayRouteChildren = {
  EmpirePlayAlbunsRoute: EmpirePlayAlbunsRoute,
  EmpirePlayAlbunsAntigosRoute: EmpirePlayAlbunsAntigosRouteWithChildren,
  EmpirePlayForumRoute: EmpirePlayForumRoute,
  EmpirePlayGestaoRoute: EmpirePlayGestaoRouteWithChildren,
  EmpirePlayMusicasRoute: EmpirePlayMusicasRoute,
  EmpirePlayVideosRoute: EmpirePlayVideosRoute,
  EmpirePlayIndexRoute: EmpirePlayIndexRoute,
  EmpirePlayPlaylistsIdRoute: EmpirePlayPlaylistsIdRouteWithChildren,
  EmpirePlayPlaylistsNovaRoute: EmpirePlayPlaylistsNovaRoute,
  EmpirePlayPlaylistsIndexRoute: EmpirePlayPlaylistsIndexRoute,
}

const EmpirePlayRouteWithChildren = EmpirePlayRoute._addFileChildren(
  EmpirePlayRouteChildren,
)

interface AlbumIdRouteChildren {
  AlbumIdEditarRoute: typeof AlbumIdEditarRoute
}

const AlbumIdRouteChildren: AlbumIdRouteChildren = {
  AlbumIdEditarRoute: AlbumIdEditarRoute,
}

const AlbumIdRouteWithChildren =
  AlbumIdRoute._addFileChildren(AlbumIdRouteChildren)

interface PontoDistribuirRouteChildren {
  PontoDistribuirPlanilhaRoute: typeof PontoDistribuirPlanilhaRoute
  PontoDistribuirIndexRoute: typeof PontoDistribuirIndexRoute
}

const PontoDistribuirRouteChildren: PontoDistribuirRouteChildren = {
  PontoDistribuirPlanilhaRoute: PontoDistribuirPlanilhaRoute,
  PontoDistribuirIndexRoute: PontoDistribuirIndexRoute,
}

const PontoDistribuirRouteWithChildren = PontoDistribuirRoute._addFileChildren(
  PontoDistribuirRouteChildren,
)

interface PontoPlaylistsRouteChildren {
  PontoPlaylistsPlanilhaRoute: typeof PontoPlaylistsPlanilhaRoute
  PontoPlaylistsIndexRoute: typeof PontoPlaylistsIndexRoute
}

const PontoPlaylistsRouteChildren: PontoPlaylistsRouteChildren = {
  PontoPlaylistsPlanilhaRoute: PontoPlaylistsPlanilhaRoute,
  PontoPlaylistsIndexRoute: PontoPlaylistsIndexRoute,
}

const PontoPlaylistsRouteWithChildren = PontoPlaylistsRoute._addFileChildren(
  PontoPlaylistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoRapidoRoute: AcessoRapidoRoute,
  AlbunsRoute: AlbunsRoute,
  ChartsRoute: ChartsRoute,
  EmpirePlayRoute: EmpirePlayRouteWithChildren,
  PerfilRoute: PerfilRoute,
  SocialRoute: SocialRoute,
  TutorialRoute: TutorialRoute,
  TvRoute: TvRoute,
  AcoesAlbumRoute: AcoesAlbumRoute,
  AcoesCinemaRoute: AcoesCinemaRoute,
  AcoesTourRoute: AcoesTourRoute,
  AlbumIdRoute: AlbumIdRouteWithChildren,
  PontoDistribuirRoute: PontoDistribuirRouteWithChildren,
  PontoPlaylistsRoute: PontoPlaylistsRouteWithChildren,
  ToursNomeRoute: ToursNomeRoute,
  ArtistasIndexRoute: ArtistasIndexRoute,
  PontoIndexRoute: PontoIndexRoute,
  ToursIndexRoute: ToursIndexRoute,
  ArtistasNomeIndexRoute: ArtistasNomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
