/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessoRapidoRouteImport } from './routes/acesso-rapido'
import { Route as AlbunsRouteImport } from './routes/albuns'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as EmpirePlayRouteImport } from './routes/empire-play'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as SocialRouteImport } from './routes/social'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as TvRouteImport } from './routes/tv'
import { Route as AcoesAlbumRouteImport } from './routes/acoes.album'
import { Route as AcoesCinemaRouteImport } from './routes/acoes.cinema'
import { Route as AcoesTourRouteImport } from './routes/acoes.tour'
import { Route as AlbumIdRouteImport } from './routes/album.$id'
import { Route as ArtistasIndexRouteImport } from './routes/artistas.index'
import { Route as EmpirePlayIndexRouteImport } from './routes/empire-play.index'
import { Route as EmpirePlayAlbunsRouteImport } from './routes/empire-play.albuns'
import { Route as EmpirePlayForumRouteImport } from './routes/empire-play.forum'
import { Route as EmpirePlayGestaoRouteImport } from './routes/empire-play.gestao'
import { Route as EmpirePlayMusicasRouteImport } from './routes/empire-play.musicas'
import { Route as EmpirePlayVideosRouteImport } from './routes/empire-play.videos'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists.index'
import { Route as PlaylistsIdRouteImport } from './routes/playlists.$id'
import { Route as PlaylistsNovaRouteImport } from './routes/playlists.nova'
import { Route as PontoIndexRouteImport } from './routes/ponto.index'
import { Route as PontoDistribuirRouteImport } from './routes/ponto.distribuir'
import { Route as PontoPlaylistsRouteImport } from './routes/ponto.playlists'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as ToursNomeRouteImport } from './routes/tours.$nome'
import { Route as AlbumIdEditarRouteImport } from './routes/album.$id.editar'
import { Route as ArtistasNomeIndexRouteImport } from './routes/artistas.$nome.index'
import { Route as ArtistasNomeBensRouteImport } from './routes/artistas.$nome.bens'
import { Route as ArtistasNomeProjetosRouteImport } from './routes/artistas.$nome.projetos'
import { Route as PlaylistsIdEditarRouteImport } from './routes/playlists.$id.editar'
import { Route as PontoDistribuirPlanilhaRouteImport } from './routes/ponto.distribuir.planilha'
import { Route as PontoPlaylistsPlanilhaRouteImport } from './routes/ponto.playlists.planilha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRapidoRoute = AcessoRapidoRouteImport.update({
  id: '/acesso-rapido',
  path: '/acesso-rapido',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbunsRoute = AlbunsRouteImport.update({
  id: '/albuns',
  path: '/albuns',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpirePlayRoute = EmpirePlayRouteImport.update({
  id: '/empire-play',
  path: '/empire-play',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesAlbumRoute = AcoesAlbumRouteImport.update({
  id: '/acoes/album',
  path: '/acoes/album',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesCinemaRoute = AcoesCinemaRouteImport.update({
  id: '/acoes/cinema',
  path: '/acoes/cinema',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesTourRoute = AcoesTourRouteImport.update({
  id: '/acoes/tour',
  path: '/acoes/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdRoute = AlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistasIndexRoute = ArtistasIndexRouteImport.update({
  id: '/artistas/',
  path: '/artistas/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpirePlayIndexRoute = EmpirePlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const EmpirePlayAlbunsRoute = EmpirePlayAlbunsRouteImport.update({
  id: '/albuns',
  path: '/albuns',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const EmpirePlayForumRoute = EmpirePlayForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const EmpirePlayGestaoRoute = EmpirePlayGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const EmpirePlayMusicasRoute = EmpirePlayMusicasRouteImport.update({
  id: '/musicas',
  path: '/musicas',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const EmpirePlayVideosRoute = EmpirePlayVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => EmpirePlayRoute,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIdRoute = PlaylistsIdRouteImport.update({
  id: '/playlists/$id',
  path: '/playlists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsNovaRoute = PlaylistsNovaRouteImport.update({
  id: '/playlists/nova',
  path: '/playlists/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoIndexRoute = PontoIndexRouteImport.update({
  id: '/ponto/',
  path: '/ponto/',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoDistribuirRoute = PontoDistribuirRouteImport.update({
  id: '/ponto/distribuir',
  path: '/ponto/distribuir',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoPlaylistsRoute = PontoPlaylistsRouteImport.update({
  id: '/ponto/playlists',
  path: '/ponto/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursNomeRoute = ToursNomeRouteImport.update({
  id: '/tours/$nome',
  path: '/tours/$nome',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdEditarRoute = AlbumIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AlbumIdRoute,
} as any)
const ArtistasNomeIndexRoute = ArtistasNomeIndexRouteImport.update({
  id: '/artistas/$nome/',
  path: '/artistas/$nome/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistasNomeBensRoute = ArtistasNomeBensRouteImport.update({
  id: '/artistas/$nome/bens',
  path: '/artistas/$nome/bens',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistasNomeProjetosRoute = ArtistasNomeProjetosRouteImport.update({
  id: '/artistas/$nome/projetos',
  path: '/artistas/$nome/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIdEditarRoute = PlaylistsIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => PlaylistsIdRoute,
} as any)
const PontoDistribuirPlanilhaRoute = PontoDistribuirPlanilhaRouteImport.update({
  id: '/planilha',
  path: '/planilha',
  getParentRoute: () => PontoDistribuirRoute,
} as any)
const PontoPlaylistsPlanilhaRoute = PontoPlaylistsPlanilhaRouteImport.update({
  id: '/planilha',
  path: '/planilha',
  getParentRoute: () => PontoPlaylistsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-rapido': typeof AcessoRapidoRoute
  '/albuns': typeof AlbunsRoute
  '/charts': typeof ChartsRoute
  '/empire-play': typeof EmpirePlayRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/social': typeof SocialRoute
  '/tutorial': typeof TutorialRoute
  '/tv': typeof TvRoute
  '/acoes/album': typeof AcoesAlbumRoute
  '/acoes/cinema': typeof AcoesCinemaRoute
  '/acoes/tour': typeof AcoesTourRoute
  '/album/$id': typeof AlbumIdRouteWithChildren
  '/empire-play/albuns': typeof EmpirePlayAlbunsRoute
  '/empire-play/forum': typeof EmpirePlayForumRoute
  '/empire-play/gestao': typeof EmpirePlayGestaoRoute
  '/empire-play/musicas': typeof EmpirePlayMusicasRoute
  '/empire-play/videos': typeof EmpirePlayVideosRoute
  '/playlists/$id': typeof PlaylistsIdRouteWithChildren
  '/playlists/nova': typeof PlaylistsNovaRoute
  '/ponto/distribuir': typeof PontoDistribuirRouteWithChildren
  '/ponto/playlists': typeof PontoPlaylistsRouteWithChildren
  '/tours/$nome': typeof ToursNomeRoute
  '/artistas/': typeof ArtistasIndexRoute
  '/empire-play/': typeof EmpirePlayIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/ponto/': typeof PontoIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/album/$id/editar': typeof AlbumIdEditarRoute
  '/artistas/$nome/bens': typeof ArtistasNomeBensRoute
  '/artistas/$nome/projetos': typeof ArtistasNomeProjetosRoute
  '/playlists/$id/editar': typeof PlaylistsIdEditarRoute
  '/ponto/distribuir/planilha': typeof PontoDistribuirPlanilhaRoute
  '/ponto/playlists/planilha': typeof PontoPlaylistsPlanilhaRoute
  '/artistas/$nome/': typeof ArtistasNomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-rapido': typeof AcessoRapidoRoute
  '/albuns': typeof AlbunsRoute
  '/charts': typeof ChartsRoute
  '/perfil': typeof PerfilRoute
  '/social': typeof SocialRoute
  '/tutorial': typeof TutorialRoute
  '/tv': typeof TvRoute
  '/acoes/album': typeof AcoesAlbumRoute
  '/acoes/cinema': typeof AcoesCinemaRoute
  '/acoes/tour': typeof AcoesTourRoute
  '/album/$id': typeof AlbumIdRouteWithChildren
  '/empire-play/albuns': typeof EmpirePlayAlbunsRoute
  '/empire-play/forum': typeof EmpirePlayForumRoute
  '/empire-play/gestao': typeof EmpirePlayGestaoRoute
  '/empire-play/musicas': typeof EmpirePlayMusicasRoute
  '/empire-play/videos': typeof EmpirePlayVideosRoute
  '/playlists/$id': typeof PlaylistsIdRouteWithChildren
  '/playlists/nova': typeof PlaylistsNovaRoute
  '/ponto/distribuir': typeof PontoDistribuirRouteWithChildren
  '/ponto/playlists': typeof PontoPlaylistsRouteWithChildren
  '/tours/$nome': typeof ToursNomeRoute
  '/artistas': typeof ArtistasIndexRoute
  '/empire-play': typeof EmpirePlayIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/ponto': typeof PontoIndexRoute
  '/tours': typeof ToursIndexRoute
  '/album/$id/editar': typeof AlbumIdEditarRoute
  '/artistas/$nome/bens': typeof ArtistasNomeBensRoute
  '/artistas/$nome/projetos': typeof ArtistasNomeProjetosRoute
  '/playlists/$id/editar': typeof PlaylistsIdEditarRoute
  '/ponto/distribuir/planilha': typeof PontoDistribuirPlanilhaRoute
  '/ponto/playlists/planilha': typeof PontoPlaylistsPlanilhaRoute
  '/artistas/$nome': typeof ArtistasNomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso-rapido': typeof AcessoRapidoRoute
  '/albuns': typeof AlbunsRoute
  '/charts': typeof ChartsRoute
  '/empire-play': typeof EmpirePlayRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/social': typeof SocialRoute
  '/tutorial': typeof TutorialRoute
  '/tv': typeof TvRoute
  '/acoes/album': typeof AcoesAlbumRoute
  '/acoes/cinema': typeof AcoesCinemaRoute
  '/acoes/tour': typeof AcoesTourRoute
  '/album/$id': typeof AlbumIdRouteWithChildren
  '/empire-play/albuns': typeof EmpirePlayAlbunsRoute
  '/empire-play/forum': typeof EmpirePlayForumRoute
  '/empire-play/gestao': typeof EmpirePlayGestaoRoute
  '/empire-play/musicas': typeof EmpirePlayMusicasRoute
  '/empire-play/videos': typeof EmpirePlayVideosRoute
  '/playlists/$id': typeof PlaylistsIdRouteWithChildren
  '/playlists/nova': typeof PlaylistsNovaRoute
  '/ponto/distribuir': typeof PontoDistribuirRouteWithChildren
  '/ponto/playlists': typeof PontoPlaylistsRouteWithChildren
  '/tours/$nome': typeof ToursNomeRoute
  '/artistas/': typeof ArtistasIndexRoute
  '/empire-play/': typeof EmpirePlayIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/ponto/': typeof PontoIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/album/$id/editar': typeof AlbumIdEditarRoute
  '/artistas/$nome/bens': typeof ArtistasNomeBensRoute
  '/artistas/$nome/projetos': typeof ArtistasNomeProjetosRoute
  '/playlists/$id/editar': typeof PlaylistsIdEditarRoute
  '/ponto/distribuir/planilha': typeof PontoDistribuirPlanilhaRoute
  '/ponto/playlists/planilha': typeof PontoPlaylistsPlanilhaRoute
  '/artistas/$nome/': typeof ArtistasNomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-rapido'
    | '/albuns'
    | '/charts'
    | '/empire-play'
    | '/perfil'
    | '/social'
    | '/tutorial'
    | '/tv'
    | '/acoes/album'
    | '/acoes/cinema'
    | '/acoes/tour'
    | '/album/$id'
    | '/empire-play/albuns'
    | '/empire-play/forum'
    | '/empire-play/gestao'
    | '/empire-play/musicas'
    | '/empire-play/videos'
    | '/playlists/$id'
    | '/playlists/nova'
    | '/ponto/distribuir'
    | '/ponto/playlists'
    | '/tours/$nome'
    | '/artistas/'
    | '/empire-play/'
    | '/playlists/'
    | '/ponto/'
    | '/tours/'
    | '/album/$id/editar'
    | '/artistas/$nome/bens'
    | '/artistas/$nome/projetos'
    | '/playlists/$id/editar'
    | '/ponto/distribuir/planilha'
    | '/ponto/playlists/planilha'
    | '/artistas/$nome/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-rapido'
    | '/albuns'
    | '/charts'
    | '/perfil'
    | '/social'
    | '/tutorial'
    | '/tv'
    | '/acoes/album'
    | '/acoes/cinema'
    | '/acoes/tour'
    | '/album/$id'
    | '/empire-play/albuns'
    | '/empire-play/forum'
    | '/empire-play/gestao'
    | '/empire-play/musicas'
    | '/empire-play/videos'
    | '/playlists/$id'
    | '/playlists/nova'
    | '/ponto/distribuir'
    | '/ponto/playlists'
    | '/tours/$nome'
    | '/artistas'
    | '/empire-play'
    | '/playlists'
    | '/ponto'
    | '/tours'
    | '/album/$id/editar'
    | '/artistas/$nome/bens'
    | '/artistas/$nome/projetos'
    | '/playlists/$id/editar'
    | '/ponto/distribuir/planilha'
    | '/ponto/playlists/planilha'
    | '/artistas/$nome'
  id:
    | '__root__'
    | '/'
    | '/acesso-rapido'
    | '/albuns'
    | '/charts'
    | '/empire-play'
    | '/perfil'
    | '/social'
    | '/tutorial'
    | '/tv'
    | '/acoes/album'
    | '/acoes/cinema'
    | '/acoes/tour'
    | '/album/$id'
    | '/empire-play/albuns'
    | '/empire-play/forum'
    | '/empire-play/gestao'
    | '/empire-play/musicas'
    | '/empire-play/videos'
    | '/playlists/$id'
    | '/playlists/nova'
    | '/ponto/distribuir'
    | '/ponto/playlists'
    | '/tours/$nome'
    | '/artistas/'
    | '/empire-play/'
    | '/playlists/'
    | '/ponto/'
    | '/tours/'
    | '/album/$id/editar'
    | '/artistas/$nome/bens'
    | '/artistas/$nome/projetos'
    | '/playlists/$id/editar'
    | '/ponto/distribuir/planilha'
    | '/ponto/playlists/planilha'
    | '/artistas/$nome/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoRapidoRoute: typeof AcessoRapidoRoute
  AlbunsRoute: typeof AlbunsRoute
  ChartsRoute: typeof ChartsRoute
  EmpirePlayRoute: typeof EmpirePlayRouteWithChildren
  PerfilRoute: typeof PerfilRoute
  SocialRoute: typeof SocialRoute
  TutorialRoute: typeof TutorialRoute
  TvRoute: typeof TvRoute
  AcoesAlbumRoute: typeof AcoesAlbumRoute
  AcoesCinemaRoute: typeof AcoesCinemaRoute
  AcoesTourRoute: typeof AcoesTourRoute
  AlbumIdRoute: typeof AlbumIdRouteWithChildren
  PlaylistsIdRoute: typeof PlaylistsIdRouteWithChildren
  PlaylistsNovaRoute: typeof PlaylistsNovaRoute
  PontoDistribuirRoute: typeof PontoDistribuirRouteWithChildren
  PontoPlaylistsRoute: typeof PontoPlaylistsRouteWithChildren
  ToursNomeRoute: typeof ToursNomeRoute
  ArtistasIndexRoute: typeof ArtistasIndexRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  PontoIndexRoute: typeof PontoIndexRoute
  ToursIndexRoute: typeof ToursIndexRoute
  ArtistasNomeBensRoute: typeof ArtistasNomeBensRoute
  ArtistasNomeProjetosRoute: typeof ArtistasNomeProjetosRoute
  ArtistasNomeIndexRoute: typeof ArtistasNomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-rapido': {
      id: '/acesso-rapido'
      path: '/acesso-rapido'
      fullPath: '/acesso-rapido'
      preLoaderRoute: typeof AcessoRapidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albuns': {
      id: '/albuns'
      path: '/albuns'
      fullPath: '/albuns'
      preLoaderRoute: typeof AlbunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empire-play': {
      id: '/empire-play'
      path: '/empire-play'
      fullPath: '/empire-play'
      preLoaderRoute: typeof EmpirePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes/album': {
      id: '/acoes/album'
      path: '/acoes/album'
      fullPath: '/acoes/album'
      preLoaderRoute: typeof AcoesAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes/cinema': {
      id: '/acoes/cinema'
      path: '/acoes/cinema'
      fullPath: '/acoes/cinema'
      preLoaderRoute: typeof AcoesCinemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes/tour': {
      id: '/acoes/tour'
      path: '/acoes/tour'
      fullPath: '/acoes/tour'
      preLoaderRoute: typeof AcoesTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id': {
      id: '/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistas/': {
      id: '/artistas/'
      path: '/artistas'
      fullPath: '/artistas/'
      preLoaderRoute: typeof ArtistasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empire-play/': {
      id: '/empire-play/'
      path: '/'
      fullPath: '/empire-play/'
      preLoaderRoute: typeof EmpirePlayIndexRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/empire-play/albuns': {
      id: '/empire-play/albuns'
      path: '/albuns'
      fullPath: '/empire-play/albuns'
      preLoaderRoute: typeof EmpirePlayAlbunsRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/empire-play/forum': {
      id: '/empire-play/forum'
      path: '/forum'
      fullPath: '/empire-play/forum'
      preLoaderRoute: typeof EmpirePlayForumRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/empire-play/gestao': {
      id: '/empire-play/gestao'
      path: '/gestao'
      fullPath: '/empire-play/gestao'
      preLoaderRoute: typeof EmpirePlayGestaoRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/empire-play/musicas': {
      id: '/empire-play/musicas'
      path: '/musicas'
      fullPath: '/empire-play/musicas'
      preLoaderRoute: typeof EmpirePlayMusicasRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/empire-play/videos': {
      id: '/empire-play/videos'
      path: '/videos'
      fullPath: '/empire-play/videos'
      preLoaderRoute: typeof EmpirePlayVideosRouteImport
      parentRoute: typeof EmpirePlayRoute
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$id': {
      id: '/playlists/$id'
      path: '/playlists/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof PlaylistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/nova': {
      id: '/playlists/nova'
      path: '/playlists/nova'
      fullPath: '/playlists/nova'
      preLoaderRoute: typeof PlaylistsNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto/': {
      id: '/ponto/'
      path: '/ponto'
      fullPath: '/ponto/'
      preLoaderRoute: typeof PontoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto/distribuir': {
      id: '/ponto/distribuir'
      path: '/ponto/distribuir'
      fullPath: '/ponto/distribuir'
      preLoaderRoute: typeof PontoDistribuirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto/playlists': {
      id: '/ponto/playlists'
      path: '/ponto/playlists'
      fullPath: '/ponto/playlists'
      preLoaderRoute: typeof PontoPlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$nome': {
      id: '/tours/$nome'
      path: '/tours/$nome'
      fullPath: '/tours/$nome'
      preLoaderRoute: typeof ToursNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id/editar': {
      id: '/album/$id/editar'
      path: '/editar'
      fullPath: '/album/$id/editar'
      preLoaderRoute: typeof AlbumIdEditarRouteImport
      parentRoute: typeof AlbumIdRoute
    }
    '/artistas/$nome/': {
      id: '/artistas/$nome/'
      path: '/artistas/$nome'
      fullPath: '/artistas/$nome/'
      preLoaderRoute: typeof ArtistasNomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistas/$nome/bens': {
      id: '/artistas/$nome/bens'
      path: '/artistas/$nome/bens'
      fullPath: '/artistas/$nome/bens'
      preLoaderRoute: typeof ArtistasNomeBensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistas/$nome/projetos': {
      id: '/artistas/$nome/projetos'
      path: '/artistas/$nome/projetos'
      fullPath: '/artistas/$nome/projetos'
      preLoaderRoute: typeof ArtistasNomeProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$id/editar': {
      id: '/playlists/$id/editar'
      path: '/editar'
      fullPath: '/playlists/$id/editar'
      preLoaderRoute: typeof PlaylistsIdEditarRouteImport
      parentRoute: typeof PlaylistsIdRoute
    }
    '/ponto/distribuir/planilha': {
      id: '/ponto/distribuir/planilha'
      path: '/planilha'
      fullPath: '/ponto/distribuir/planilha'
      preLoaderRoute: typeof PontoDistribuirPlanilhaRouteImport
      parentRoute: typeof PontoDistribuirRoute
    }
    '/ponto/playlists/planilha': {
      id: '/ponto/playlists/planilha'
      path: '/planilha'
      fullPath: '/ponto/playlists/planilha'
      preLoaderRoute: typeof PontoPlaylistsPlanilhaRouteImport
      parentRoute: typeof PontoPlaylistsRoute
    }
  }
}

interface EmpirePlayRouteChildren {
  EmpirePlayAlbunsRoute: typeof EmpirePlayAlbunsRoute
  EmpirePlayForumRoute: typeof EmpirePlayForumRoute
  EmpirePlayGestaoRoute: typeof EmpirePlayGestaoRoute
  EmpirePlayMusicasRoute: typeof EmpirePlayMusicasRoute
  EmpirePlayVideosRoute: typeof EmpirePlayVideosRoute
  EmpirePlayIndexRoute: typeof EmpirePlayIndexRoute
}

const EmpirePlayRouteChildren: EmpirePlayRouteChildren = {
  EmpirePlayAlbunsRoute: EmpirePlayAlbunsRoute,
  EmpirePlayForumRoute: EmpirePlayForumRoute,
  EmpirePlayGestaoRoute: EmpirePlayGestaoRoute,
  EmpirePlayMusicasRoute: EmpirePlayMusicasRoute,
  EmpirePlayVideosRoute: EmpirePlayVideosRoute,
  EmpirePlayIndexRoute: EmpirePlayIndexRoute,
}

const EmpirePlayRouteWithChildren = EmpirePlayRoute._addFileChildren(
  EmpirePlayRouteChildren,
)

interface AlbumIdRouteChildren {
  AlbumIdEditarRoute: typeof AlbumIdEditarRoute
}

const AlbumIdRouteChildren: AlbumIdRouteChildren = {
  AlbumIdEditarRoute: AlbumIdEditarRoute,
}

const AlbumIdRouteWithChildren =
  AlbumIdRoute._addFileChildren(AlbumIdRouteChildren)

interface PlaylistsIdRouteChildren {
  PlaylistsIdEditarRoute: typeof PlaylistsIdEditarRoute
}

const PlaylistsIdRouteChildren: PlaylistsIdRouteChildren = {
  PlaylistsIdEditarRoute: PlaylistsIdEditarRoute,
}

const PlaylistsIdRouteWithChildren = PlaylistsIdRoute._addFileChildren(
  PlaylistsIdRouteChildren,
)

interface PontoDistribuirRouteChildren {
  PontoDistribuirPlanilhaRoute: typeof PontoDistribuirPlanilhaRoute
}

const PontoDistribuirRouteChildren: PontoDistribuirRouteChildren = {
  PontoDistribuirPlanilhaRoute: PontoDistribuirPlanilhaRoute,
}

const PontoDistribuirRouteWithChildren = PontoDistribuirRoute._addFileChildren(
  PontoDistribuirRouteChildren,
)

interface PontoPlaylistsRouteChildren {
  PontoPlaylistsPlanilhaRoute: typeof PontoPlaylistsPlanilhaRoute
}

const PontoPlaylistsRouteChildren: PontoPlaylistsRouteChildren = {
  PontoPlaylistsPlanilhaRoute: PontoPlaylistsPlanilhaRoute,
}

const PontoPlaylistsRouteWithChildren = PontoPlaylistsRoute._addFileChildren(
  PontoPlaylistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoRapidoRoute: AcessoRapidoRoute,
  AlbunsRoute: AlbunsRoute,
  ChartsRoute: ChartsRoute,
  EmpirePlayRoute: EmpirePlayRouteWithChildren,
  PerfilRoute: PerfilRoute,
  SocialRoute: SocialRoute,
  TutorialRoute: TutorialRoute,
  TvRoute: TvRoute,
  AcoesAlbumRoute: AcoesAlbumRoute,
  AcoesCinemaRoute: AcoesCinemaRoute,
  AcoesTourRoute: AcoesTourRoute,
  AlbumIdRoute: AlbumIdRouteWithChildren,
  PlaylistsIdRoute: PlaylistsIdRouteWithChildren,
  PlaylistsNovaRoute: PlaylistsNovaRoute,
  PontoDistribuirRoute: PontoDistribuirRouteWithChildren,
  PontoPlaylistsRoute: PontoPlaylistsRouteWithChildren,
  ToursNomeRoute: ToursNomeRoute,
  ArtistasIndexRoute: ArtistasIndexRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  PontoIndexRoute: PontoIndexRoute,
  ToursIndexRoute: ToursIndexRoute,
  ArtistasNomeBensRoute: ArtistasNomeBensRoute,
  ArtistasNomeProjetosRoute: ArtistasNomeProjetosRoute,
  ArtistasNomeIndexRoute: ArtistasNomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
